{
  imports = [
    ./browser/brave.nix
    ./browser/firefox.nix
    ./browser/chromium.nix
    ./infomatic/mendeley.nix
    ./infomatic/only-office.nix
    ./infomatic/libreoffice.nix
    ./infomatic/obs-studio.nix
    ./infomatic/gradia.nix
    ./infomatic/planify.nix
    ./infomatic/teams.nix
    ./infomatic/affine.nix
    ./infomatic/wordbook.nix
    ./infomatic/foliate.nix
    ./infomatic/geary.nix
    ./infomatic/logseq.nix
    ./music/spotify.nix
    ./music/spotube.nix
    ./music/gapless.nix
    ./messaging/signal.nix
    ./messaging/telegram.nix
    ./messaging/karere.nix
    ./messaging/discord.nix
    ./messaging/element.nix
    ./others/denaro.nix
    ./others/secrets.nix
    ./others/tangram.nix
    ./others/ferdium.nix
    ./others/overleaf.nix
  ];
}
