{
  imports = [
    ./browser/brave.nix
    ./browser/firefox.nix
    ./browser/chromium.nix
    ./infomatic/mendeley.nix
    ./infomatic/only-office.nix
    ./infomatic/libreoffice.nix
    ./infomatic/video-editing.nix
    ./infomatic/gradia.nix
    ./infomatic/planify.nix
    ./infomatic/teams.nix
    ./infomatic/affine.nix
    ./infomatic/wordbook.nix
    ./infomatic/foliate.nix
    ./infomatic/geary.nix
    ./music/spotify.nix
    ./music/spotube.nix
    ./music/gapless.nix
    ./others/discord.nix
    ./others/element.nix
    ./others/tangram.nix
    ./others/ferdium.nix
    ./others/signal.nix
  ];
}
